spring:
  application:
    name: javapractice
server:
  tomcat:
    threads:
      max: 200                # ??? ? ?? thread? ? ??
    max-connections: 8192     # ????? connection? ? ??
    accept-count: 100         # ???? ???
    connection-timeout: 20000 # timeout ?? ?? ??, 20?

